name: Generate trophy

on:
  schedule: # 03:00 JST == 18:00 UTC
    - cron: "0 18 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-trophy
    steps:
      - uses: actions/checkout@v5
      - uses: Erik-Donath/github-profile-trophy@feature/generate-svg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
        with:
          file: Trophy/trophy.svg
          token: ${{ secrets.GITHUB_TOKEN }}
